spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      database: 0
      host: '127.0.0.1'
      password: ''
      jedis:
        pool:
          max-active: 200
          max-idle: 10
          max-wait: -1ms
          min-idle: 0
      port: 6379
      timeout: 1000ms

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.jozz.entity

#showSql
logging:
  level:
    com.jozz.alex.mapper : debug

